name: Gang
version: ${project.version}
main: com.redspeaks.gang.GangPlugin
api-version: 1.16
depend: [Vault,RevEnchants]
commands:
   gang:
    description: main command
    aliases: [gangs]
   gangman:
    description: gang manager command
    aliases: [gangmanager]